apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ecadraft 
spec:
  hosts:
  - "*" 
  gateways:
  - ecadraft-gateway
  http:
  - route:
    - destination:
        host: ecadraft
        subset: v2
      weight: 50
