apiVersion: v1
kind: Service
metadata:
  name: ecadraft1
  labels:
    app: ecadraft1
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: ecadraft1
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ecadraft1-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ecadraft1
        version: v1
    spec:
      containers:
      - name: ecadraft1
        image: iad.ocir.io/innovatemcafee2/eca-$COMPARTMENT:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
