apiVersion: v1
kind: Service
metadata:
  name: ecadraft3
  labels:
    app: ecadraft3
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: ecadraft3
 --
 apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ecadraft3-v1
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: ecadraft3
        version: v1
    spec:
      containers:
      - name: ecadraft3
        image: iad.ocir.io/innovatemcafee2/eca-$COMPARTMENT:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
      imagePullSecrets:
      - name: regcred
